#!/bin/bash
# Comprehensive System Hardening Script
# Generated by Blue Team Remediation Engine

set -e

echo "============================================"
echo "SYSTEM HARDENING SCRIPT"
echo "============================================"
echo "Starting system hardening at: $(date)"
echo ""

# Update system
echo "[1/10] Updating system packages..."
sudo apt update && sudo apt upgrade -y

# Configure firewall
echo "[2/10] Configuring firewall..."
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw --force enable

# Secure SSH configuration
echo "[3/10] Hardening SSH configuration..."
sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)

# SSH hardening settings
sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sudo sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
sudo sed -i 's/#MaxAuthTries 6/MaxAuthTries 3/' /etc/ssh/sshd_config
sudo sed -i 's/#ClientAliveInterval 0/ClientAliveInterval 300/' /etc/ssh/sshd_config
sudo sed -i 's/#ClientAliveCountMax 3/ClientAliveCountMax 2/' /etc/ssh/sshd_config

# Test SSH configuration
sudo sshd -t
sudo systemctl restart sshd

# Configure fail2ban
echo "[4/10] Installing and configuring fail2ban..."
sudo apt install fail2ban -y

sudo tee /etc/fail2ban/jail.local > /dev/null <<EOF
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3

[sshd]
enabled = true
port = ssh
logpath = /var/log/auth.log
maxretry = 3
EOF

sudo systemctl enable fail2ban
sudo systemctl start fail2ban

# Disable unnecessary services
echo "[5/10] Disabling unnecessary services..."
services_to_disable=(
    "telnet"
    "rsh"
    "rlogin"
    "finger"
    "talk"
    "ntalk"
)

for service in "${services_to_disable[@]}"; do
    if systemctl is-enabled $service 2>/dev/null; then
        sudo systemctl disable $service
        sudo systemctl stop $service
        echo "Disabled: $service"
    fi
done

# Secure kernel parameters
echo "[6/10] Configuring kernel security parameters..."
sudo tee /etc/sysctl.d/99-security.conf > /dev/null <<EOF
# IP Spoofing protection
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1

# Ignore ICMP ping requests
net.ipv4.icmp_echo_ignore_all = 1

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0

# Log Martians
net.ipv4.conf.all.log_martians = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Disable IPv6 if not needed
net.ipv6.conf.all.disable_ipv6 = 1
EOF

sudo sysctl -p /etc/sysctl.d/99-security.conf

# Set up log monitoring
echo "[7/10] Configuring log monitoring..."
sudo apt install logwatch -y

# Configure automatic security updates
echo "[8/10] Enabling automatic security updates..."
sudo apt install unattended-upgrades -y
sudo dpkg-reconfigure -plow unattended-upgrades

# Install and configure antivirus
echo "[9/10] Installing ClamAV antivirus..."
sudo apt install clamav clamav-daemon -y
sudo freshclam
sudo systemctl enable clamav-daemon

# File permission hardening
echo "[10/10] Hardening file permissions..."
sudo chmod 700 /root
sudo chmod 644 /etc/passwd
sudo chmod 600 /etc/shadow
sudo chmod 644 /etc/group

echo "============================================"
echo "SYSTEM HARDENING COMPLETED"
echo "============================================"
echo "Summary:"
echo "✓ System packages updated"
echo "✓ Firewall configured and enabled"
echo "✓ SSH hardened"
echo "✓ Fail2ban installed and configured"
echo "✓ Unnecessary services disabled"
echo "✓ Kernel security parameters set"
echo "✓ Log monitoring configured"
echo "✓ Automatic updates enabled"
echo "✓ Antivirus installed"
echo "✓ File permissions hardened"
echo ""
echo "Please reboot the system to ensure all changes take effect."
echo "Hardening completed at: $(date)"
